// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddObservationInput struct {
	InspectionID            string          `json:"inspectionId"`
	ObservationType         ObservationType `json:"observationType"`
	StructuredData          map[string]any  `json:"structuredData,omitempty"`
	RawVoiceURL             *string         `json:"rawVoiceUrl,omitempty"`
	Transcription           *string         `json:"transcription,omitempty"`
	TranscriptionConfidence *float64        `json:"transcriptionConfidence,omitempty"`
}

// A beeyard location containing one or more hives.
type Apiary struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Latitude        *float64  `json:"latitude,omitempty"`
	Longitude       *float64  `json:"longitude,omitempty"`
	Region          string    `json:"region"`
	ElevationOffset float64   `json:"elevationOffset"`
	BloomOffset     int       `json:"bloomOffset"`
	Hives           []*Hive   `json:"hives"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// Immutable audit event for compliance and traceability.
type AuditEvent struct {
	ID             string         `json:"id"`
	EventType      string         `json:"eventType"`
	ActorID        string         `json:"actorId"`
	TenantID       string         `json:"tenantId"`
	OccurredAt     time.Time      `json:"occurredAt"`
	PayloadVersion int            `json:"payloadVersion"`
	Payload        map[string]any `json:"payload"`
}

type CreateApiaryInput struct {
	Name            string   `json:"name"`
	Latitude        *float64 `json:"latitude,omitempty"`
	Longitude       *float64 `json:"longitude,omitempty"`
	Region          string   `json:"region"`
	ElevationOffset *float64 `json:"elevationOffset,omitempty"`
	BloomOffset     *int     `json:"bloomOffset,omitempty"`
}

type CreateHiveInput struct {
	ApiaryID string   `json:"apiaryId"`
	Name     string   `json:"name"`
	Type     HiveType `json:"type"`
	Notes    *string  `json:"notes,omitempty"`
}

type DeferTaskInput struct {
	Reason *string `json:"reason,omitempty"`
}

// Standard error extensions returned in GraphQL error responses.
// Every domain error includes a machine-readable code, a human message, and retryability.
type ErrorExtensions struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

// Structured reference to an evidence source supporting a recommendation.
type EvidenceSource struct {
	SourceType     string  `json:"sourceType"`
	SourceID       string  `json:"sourceId"`
	RelevanceScore float64 `json:"relevanceScore"`
	Summary        string  `json:"summary"`
}

type ExportDataInput struct {
	Format ExportFormat `json:"format"`
}

// An export job that generates a downloadable file.
type ExportJob struct {
	ID          string       `json:"id"`
	Format      ExportFormat `json:"format"`
	Status      ExportStatus `json:"status"`
	DownloadURL *string      `json:"downloadUrl,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	CompletedAt *time.Time   `json:"completedAt,omitempty"`
}

// A single hive within an apiary.
type Hive struct {
	ID        string     `json:"id"`
	Apiary    *Apiary    `json:"apiary"`
	Name      string     `json:"name"`
	Type      HiveType   `json:"type"`
	Status    HiveStatus `json:"status"`
	Notes     string     `json:"notes"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// A structured inspection session for a specific hive.
type Inspection struct {
	ID           string           `json:"id"`
	Hive         *Hive            `json:"hive"`
	Type         InspectionType   `json:"type"`
	Status       InspectionStatus `json:"status"`
	Observations []*Observation   `json:"observations"`
	StartedAt    time.Time        `json:"startedAt"`
	CompletedAt  *time.Time       `json:"completedAt,omitempty"`
	Notes        string           `json:"notes"`
	CreatedAt    time.Time        `json:"createdAt"`
}

// Media attachment (photo, audio) linked to an observation.
type Media struct {
	ID             string         `json:"id"`
	StoragePath    string         `json:"storagePath"`
	ContentType    string         `json:"contentType"`
	AnalysisStatus string         `json:"analysisStatus"`
	AnalysisResult map[string]any `json:"analysisResult,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type Mutation struct {
}

// A single observation recorded during an inspection.
type Observation struct {
	ID                      string          `json:"id"`
	Inspection              *Inspection     `json:"inspection"`
	SequenceOrder           int             `json:"sequenceOrder"`
	ObservationType         ObservationType `json:"observationType"`
	StructuredData          map[string]any  `json:"structuredData,omitempty"`
	RawVoiceURL             *string         `json:"rawVoiceUrl,omitempty"`
	Transcription           *string         `json:"transcription,omitempty"`
	TranscriptionConfidence *float64        `json:"transcriptionConfidence,omitempty"`
	Media                   []*Media        `json:"media"`
	CreatedAt               time.Time       `json:"createdAt"`
}

type Query struct {
}

// AI-generated recommendation with mandatory contract fields.
// Every recommendation surface must return action + rationale + confidence + fallback.
type Recommendation struct {
	ID                      string            `json:"id"`
	Hive                    *Hive             `json:"hive"`
	Action                  string            `json:"action"`
	Rationale               string            `json:"rationale"`
	ConfidenceLevel         float64           `json:"confidenceLevel"`
	ConfidenceType          ConfidenceType    `json:"confidenceType"`
	FallbackAction          string            `json:"fallbackAction"`
	EvidenceContext         map[string]any    `json:"evidenceContext,omitempty"`
	EvidenceSources         []*EvidenceSource `json:"evidenceSources,omitempty"`
	SkillAdaptedExplanation string            `json:"skillAdaptedExplanation"`
	CreatedAt               time.Time         `json:"createdAt"`
	ExpiresAt               *time.Time        `json:"expiresAt,omitempty"`
}

type StartInspectionInput struct {
	HiveID string         `json:"hiveId"`
	Type   InspectionType `json:"type"`
}

// An actionable task derived from a recommendation.
type Task struct {
	ID              string          `json:"id"`
	Recommendation  *Recommendation `json:"recommendation,omitempty"`
	Hive            *Hive           `json:"hive"`
	Title           string          `json:"title"`
	Priority        TaskPriority    `json:"priority"`
	Status          TaskStatus      `json:"status"`
	DueDate         *time.Time      `json:"dueDate,omitempty"`
	DeferredReason  *string         `json:"deferredReason,omitempty"`
	CompletedAt     *time.Time      `json:"completedAt,omitempty"`
	IsOverdue       bool            `json:"isOverdue"`
	CatchUpGuidance *string         `json:"catchUpGuidance,omitempty"`
	CreatedAt       time.Time       `json:"createdAt"`
}

type UpdateApiaryInput struct {
	Name            *string  `json:"name,omitempty"`
	Latitude        *float64 `json:"latitude,omitempty"`
	Longitude       *float64 `json:"longitude,omitempty"`
	Region          *string  `json:"region,omitempty"`
	ElevationOffset *float64 `json:"elevationOffset,omitempty"`
	BloomOffset     *int     `json:"bloomOffset,omitempty"`
}

type UpdateHiveInput struct {
	Name   *string     `json:"name,omitempty"`
	Type   *HiveType   `json:"type,omitempty"`
	Status *HiveStatus `json:"status,omitempty"`
	Notes  *string     `json:"notes,omitempty"`
}

// Authenticated user profile.
type User struct {
	ID              string          `json:"id"`
	Email           string          `json:"email"`
	DisplayName     string          `json:"displayName"`
	ExperienceLevel ExperienceLevel `json:"experienceLevel"`
	Region          string          `json:"region"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

// Confidence classification for AI-generated recommendations.
type ConfidenceType string

const (
	ConfidenceTypeHigh                ConfidenceType = "HIGH"
	ConfidenceTypeModerate            ConfidenceType = "MODERATE"
	ConfidenceTypeLow                 ConfidenceType = "LOW"
	ConfidenceTypeInsufficientData    ConfidenceType = "INSUFFICIENT_DATA"
	ConfidenceTypeConflictingEvidence ConfidenceType = "CONFLICTING_EVIDENCE"
	ConfidenceTypeLimitedExperience   ConfidenceType = "LIMITED_EXPERIENCE"
)

var AllConfidenceType = []ConfidenceType{
	ConfidenceTypeHigh,
	ConfidenceTypeModerate,
	ConfidenceTypeLow,
	ConfidenceTypeInsufficientData,
	ConfidenceTypeConflictingEvidence,
	ConfidenceTypeLimitedExperience,
}

func (e ConfidenceType) IsValid() bool {
	switch e {
	case ConfidenceTypeHigh, ConfidenceTypeModerate, ConfidenceTypeLow, ConfidenceTypeInsufficientData, ConfidenceTypeConflictingEvidence, ConfidenceTypeLimitedExperience:
		return true
	}
	return false
}

func (e ConfidenceType) String() string {
	return string(e)
}

func (e *ConfidenceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConfidenceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConfidenceType", str)
	}
	return nil
}

func (e ConfidenceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConfidenceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConfidenceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Experience level of the beekeeper.
type ExperienceLevel string

const (
	ExperienceLevelNewbie    ExperienceLevel = "NEWBIE"
	ExperienceLevelAmateur   ExperienceLevel = "AMATEUR"
	ExperienceLevelSideliner ExperienceLevel = "SIDELINER"
)

var AllExperienceLevel = []ExperienceLevel{
	ExperienceLevelNewbie,
	ExperienceLevelAmateur,
	ExperienceLevelSideliner,
}

func (e ExperienceLevel) IsValid() bool {
	switch e {
	case ExperienceLevelNewbie, ExperienceLevelAmateur, ExperienceLevelSideliner:
		return true
	}
	return false
}

func (e ExperienceLevel) String() string {
	return string(e)
}

func (e *ExperienceLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperienceLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperienceLevel", str)
	}
	return nil
}

func (e ExperienceLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperienceLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperienceLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Export file format.
type ExportFormat string

const (
	ExportFormatJSON ExportFormat = "JSON"
	ExportFormatCSV  ExportFormat = "CSV"
)

var AllExportFormat = []ExportFormat{
	ExportFormatJSON,
	ExportFormatCSV,
}

func (e ExportFormat) IsValid() bool {
	switch e {
	case ExportFormatJSON, ExportFormatCSV:
		return true
	}
	return false
}

func (e ExportFormat) String() string {
	return string(e)
}

func (e *ExportFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExportFormat", str)
	}
	return nil
}

func (e ExportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExportFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExportFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Status of an export job.
type ExportStatus string

const (
	ExportStatusPending    ExportStatus = "PENDING"
	ExportStatusProcessing ExportStatus = "PROCESSING"
	ExportStatusCompleted  ExportStatus = "COMPLETED"
	ExportStatusFailed     ExportStatus = "FAILED"
)

var AllExportStatus = []ExportStatus{
	ExportStatusPending,
	ExportStatusProcessing,
	ExportStatusCompleted,
	ExportStatusFailed,
}

func (e ExportStatus) IsValid() bool {
	switch e {
	case ExportStatusPending, ExportStatusProcessing, ExportStatusCompleted, ExportStatusFailed:
		return true
	}
	return false
}

func (e ExportStatus) String() string {
	return string(e)
}

func (e *ExportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExportStatus", str)
	}
	return nil
}

func (e ExportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Current operational status of a hive.
type HiveStatus string

const (
	HiveStatusActive   HiveStatus = "ACTIVE"
	HiveStatusInactive HiveStatus = "INACTIVE"
	HiveStatusDead     HiveStatus = "DEAD"
	HiveStatusSold     HiveStatus = "SOLD"
)

var AllHiveStatus = []HiveStatus{
	HiveStatusActive,
	HiveStatusInactive,
	HiveStatusDead,
	HiveStatusSold,
}

func (e HiveStatus) IsValid() bool {
	switch e {
	case HiveStatusActive, HiveStatusInactive, HiveStatusDead, HiveStatusSold:
		return true
	}
	return false
}

func (e HiveStatus) String() string {
	return string(e)
}

func (e *HiveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HiveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HiveStatus", str)
	}
	return nil
}

func (e HiveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HiveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HiveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hive type classification.
type HiveType string

const (
	HiveTypeLangstroth HiveType = "LANGSTROTH"
	HiveTypeTopBar     HiveType = "TOP_BAR"
	HiveTypeWarre      HiveType = "WARRE"
	HiveTypeOther      HiveType = "OTHER"
)

var AllHiveType = []HiveType{
	HiveTypeLangstroth,
	HiveTypeTopBar,
	HiveTypeWarre,
	HiveTypeOther,
}

func (e HiveType) IsValid() bool {
	switch e {
	case HiveTypeLangstroth, HiveTypeTopBar, HiveTypeWarre, HiveTypeOther:
		return true
	}
	return false
}

func (e HiveType) String() string {
	return string(e)
}

func (e *HiveType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HiveType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HiveType", str)
	}
	return nil
}

func (e HiveType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HiveType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HiveType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Current status of an inspection session.
type InspectionStatus string

const (
	InspectionStatusInProgress InspectionStatus = "IN_PROGRESS"
	InspectionStatusPaused     InspectionStatus = "PAUSED"
	InspectionStatusCompleted  InspectionStatus = "COMPLETED"
)

var AllInspectionStatus = []InspectionStatus{
	InspectionStatusInProgress,
	InspectionStatusPaused,
	InspectionStatusCompleted,
}

func (e InspectionStatus) IsValid() bool {
	switch e {
	case InspectionStatusInProgress, InspectionStatusPaused, InspectionStatusCompleted:
		return true
	}
	return false
}

func (e InspectionStatus) String() string {
	return string(e)
}

func (e *InspectionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InspectionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InspectionStatus", str)
	}
	return nil
}

func (e InspectionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InspectionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InspectionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Type of inspection performed.
type InspectionType string

const (
	InspectionTypeFull  InspectionType = "FULL"
	InspectionTypeQuick InspectionType = "QUICK"
)

var AllInspectionType = []InspectionType{
	InspectionTypeFull,
	InspectionTypeQuick,
}

func (e InspectionType) IsValid() bool {
	switch e {
	case InspectionTypeFull, InspectionTypeQuick:
		return true
	}
	return false
}

func (e InspectionType) String() string {
	return string(e)
}

func (e *InspectionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InspectionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InspectionType", str)
	}
	return nil
}

func (e InspectionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InspectionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InspectionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Category of observation recorded during an inspection.
type ObservationType string

const (
	ObservationTypeBroodPattern ObservationType = "BROOD_PATTERN"
	ObservationTypeQueenStatus  ObservationType = "QUEEN_STATUS"
	ObservationTypeStores       ObservationType = "STORES"
	ObservationTypePestDisease  ObservationType = "PEST_DISEASE"
	ObservationTypeTemperament  ObservationType = "TEMPERAMENT"
	ObservationTypeEquipment    ObservationType = "EQUIPMENT"
	ObservationTypeGeneral      ObservationType = "GENERAL"
)

var AllObservationType = []ObservationType{
	ObservationTypeBroodPattern,
	ObservationTypeQueenStatus,
	ObservationTypeStores,
	ObservationTypePestDisease,
	ObservationTypeTemperament,
	ObservationTypeEquipment,
	ObservationTypeGeneral,
}

func (e ObservationType) IsValid() bool {
	switch e {
	case ObservationTypeBroodPattern, ObservationTypeQueenStatus, ObservationTypeStores, ObservationTypePestDisease, ObservationTypeTemperament, ObservationTypeEquipment, ObservationTypeGeneral:
		return true
	}
	return false
}

func (e ObservationType) String() string {
	return string(e)
}

func (e *ObservationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ObservationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ObservationType", str)
	}
	return nil
}

func (e ObservationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ObservationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ObservationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Task priority level.
type TaskPriority string

const (
	TaskPriorityCritical TaskPriority = "CRITICAL"
	TaskPriorityHigh     TaskPriority = "HIGH"
	TaskPriorityMedium   TaskPriority = "MEDIUM"
	TaskPriorityLow      TaskPriority = "LOW"
)

var AllTaskPriority = []TaskPriority{
	TaskPriorityCritical,
	TaskPriorityHigh,
	TaskPriorityMedium,
	TaskPriorityLow,
}

func (e TaskPriority) IsValid() bool {
	switch e {
	case TaskPriorityCritical, TaskPriorityHigh, TaskPriorityMedium, TaskPriorityLow:
		return true
	}
	return false
}

func (e TaskPriority) String() string {
	return string(e)
}

func (e *TaskPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskPriority", str)
	}
	return nil
}

func (e TaskPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Task lifecycle status.
type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "PENDING"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusCompleted  TaskStatus = "COMPLETED"
	TaskStatusDeferred   TaskStatus = "DEFERRED"
	TaskStatusDismissed  TaskStatus = "DISMISSED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusPending,
	TaskStatusInProgress,
	TaskStatusCompleted,
	TaskStatusDeferred,
	TaskStatusDismissed,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusPending, TaskStatusInProgress, TaskStatusCompleted, TaskStatusDeferred, TaskStatusDismissed:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
