package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
	"github.com/broodly/api/internal/repository"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateApiary is the resolver for the createApiary field.
func (r *mutationResolver) CreateApiary(ctx context.Context, input model.CreateApiaryInput) (*model.Apiary, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)

	var lat, lon pgtype.Float8
	if input.Latitude != nil {
		lat = pgtype.Float8{Float64: *input.Latitude, Valid: true}
	}
	if input.Longitude != nil {
		lon = pgtype.Float8{Float64: *input.Longitude, Valid: true}
	}
	var elevOff float64
	if input.ElevationOffset != nil {
		elevOff = *input.ElevationOffset
	}
	var bloomOff int32
	if input.BloomOffset != nil {
		bloomOff = int32(*input.BloomOffset)
	}

	apiary, err := r.ApiaryService.Create(ctx, userID, repository.CreateApiaryParams{
		Name:            input.Name,
		Latitude:        lat,
		Longitude:       lon,
		Region:          input.Region,
		ElevationOffset: elevOff,
		BloomOffset:     bloomOff,
	})
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return apiaryToModel(apiary), nil
}

// UpdateApiary is the resolver for the updateApiary field.
func (r *mutationResolver) UpdateApiary(ctx context.Context, id string, input model.UpdateApiaryInput) (*model.Apiary, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	apiaryID := stringToUUID(id)

	// Build update params from current values + input overrides
	current, err := r.ApiaryService.GetByID(ctx, apiaryID, userID)
	if err != nil {
		return nil, domain.NotFoundError(ctx, "apiary")
	}

	params := repository.UpdateApiaryParams{
		Name:            current.Name,
		Latitude:        current.Latitude,
		Longitude:       current.Longitude,
		Region:          current.Region,
		ElevationOffset: current.ElevationOffset,
		BloomOffset:     current.BloomOffset,
	}
	if input.Name != nil {
		params.Name = *input.Name
	}
	if input.Latitude != nil {
		params.Latitude = pgtype.Float8{Float64: *input.Latitude, Valid: true}
	}
	if input.Longitude != nil {
		params.Longitude = pgtype.Float8{Float64: *input.Longitude, Valid: true}
	}
	if input.Region != nil {
		params.Region = *input.Region
	}
	if input.ElevationOffset != nil {
		params.ElevationOffset = *input.ElevationOffset
	}
	if input.BloomOffset != nil {
		params.BloomOffset = int32(*input.BloomOffset)
	}

	apiary, err := r.ApiaryService.Update(ctx, apiaryID, userID, params)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return apiaryToModel(apiary), nil
}

// DeleteApiary is the resolver for the deleteApiary field.
func (r *mutationResolver) DeleteApiary(ctx context.Context, id string) (bool, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	apiaryID := stringToUUID(id)

	if err := r.ApiaryService.Delete(ctx, apiaryID, userID); err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return false, domain.ToGraphQLError(ctx, domErr)
		}
		return false, err
	}
	return true, nil
}

// Apiaries is the resolver for the apiaries field.
func (r *queryResolver) Apiaries(ctx context.Context) ([]*model.Apiary, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)

	apiaries, err := r.ApiaryService.List(ctx, userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Apiary, len(apiaries))
	for i, a := range apiaries {
		result[i] = apiaryToModel(a)
	}
	return result, nil
}

// Apiary is the resolver for the apiary field.
func (r *queryResolver) Apiary(ctx context.Context, id string) (*model.Apiary, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	apiaryID := stringToUUID(id)

	apiary, err := r.ApiaryService.GetByID(ctx, apiaryID, userID)
	if err != nil {
		return nil, domain.NotFoundError(ctx, "apiary")
	}
	return apiaryToModel(apiary), nil
}
