package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
)

// ExportData is the resolver for the exportData field.
func (r *mutationResolver) ExportData(ctx context.Context, input model.ExportDataInput) (*model.ExportJob, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	format := domain.ExportFormat(strings.ToLower(string(input.Format)))

	job, err := r.ExportService.Export(ctx, userID, format)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}

	result := &model.ExportJob{
		ID:          job.ID,
		Format:      model.ExportFormat(strings.ToUpper(string(job.Format))),
		Status:      model.ExportStatus(strings.ToUpper(string(job.Status))),
		DownloadURL: &job.DownloadURL,
		CreatedAt:   job.CreatedAt,
	}
	if job.CompletedAt != nil {
		result.CompletedAt = job.CompletedAt
	}
	return result, nil
}

// ExportJobStatus is the resolver for the exportJobStatus field.
func (r *queryResolver) ExportJobStatus(ctx context.Context, id string) (*model.ExportJob, error) {
	// Async job polling will be implemented when Pub/Sub worker is added.
	return nil, domain.NotFoundError(ctx, "export job")
}
