package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
	"github.com/broodly/api/internal/repository"
)

// CreateHive is the resolver for the createHive field.
func (r *mutationResolver) CreateHive(ctx context.Context, input model.CreateHiveInput) (*model.Hive, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)

	if input.Name == "" {
		return nil, domain.ValidationError(ctx, "hive name is required")
	}

	hive, err := r.HiveService.Create(ctx, userID, repository.CreateHiveParams{
		ApiaryID: stringToUUID(input.ApiaryID),
		Name:     input.Name,
		Type:     strings.ToLower(string(input.Type)),
		Status:   "active",
		Notes:    derefString(input.Notes),
	})
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return hiveToModel(hive), nil
}

// UpdateHive is the resolver for the updateHive field.
func (r *mutationResolver) UpdateHive(ctx context.Context, id string, input model.UpdateHiveInput) (*model.Hive, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	hiveID := stringToUUID(id)
	userID := stringToUUID(uid)

	// Verify ownership
	current, err := r.HiveService.GetByIDAndUser(ctx, hiveID, userID)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}

	params := repository.UpdateHiveParams{
		Name:   current.Name,
		Type:   current.Type,
		Status: current.Status,
		Notes:  current.Notes,
	}
	if input.Name != nil {
		params.Name = *input.Name
	}
	if input.Type != nil {
		params.Type = strings.ToLower(string(*input.Type))
	}
	if input.Status != nil {
		params.Status = strings.ToLower(string(*input.Status))
	}
	if input.Notes != nil {
		params.Notes = *input.Notes
	}

	hive, err := r.HiveService.Update(ctx, hiveID, params)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return hiveToModel(hive), nil
}

// DeleteHive is the resolver for the deleteHive field.
func (r *mutationResolver) DeleteHive(ctx context.Context, id string) (bool, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, domain.ForbiddenError(ctx)
	}
	hiveID := stringToUUID(id)
	userID := stringToUUID(uid)

	// Verify ownership
	_, err = r.HiveService.GetByIDAndUser(ctx, hiveID, userID)
	if err != nil {
		return false, domain.ForbiddenError(ctx)
	}

	if err := r.HiveService.Delete(ctx, hiveID); err != nil {
		return false, err
	}
	return true, nil
}

// Hives is the resolver for the hives field.
func (r *queryResolver) Hives(ctx context.Context, apiaryID string) ([]*model.Hive, error) {
	hives, err := r.HiveService.List(ctx, stringToUUID(apiaryID))
	if err != nil {
		return nil, err
	}

	result := make([]*model.Hive, len(hives))
	for i, h := range hives {
		result[i] = hiveToModel(h)
	}
	return result, nil
}

// Hive is the resolver for the hive field.
func (r *queryResolver) Hive(ctx context.Context, id string) (*model.Hive, error) {
	hive, err := r.HiveService.GetByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, domain.NotFoundError(ctx, "hive")
	}
	return hiveToModel(hive), nil
}
