package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"encoding/json"
	"strings"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
	"github.com/broodly/api/internal/repository"
	"github.com/jackc/pgx/v5/pgtype"
)

// StartInspection is the resolver for the startInspection field.
func (r *mutationResolver) StartInspection(ctx context.Context, input model.StartInspectionInput) (*model.Inspection, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	hiveID := stringToUUID(input.HiveID)

	// Verify ownership via hive service
	_, err = r.HiveService.GetByIDAndUser(ctx, hiveID, userID)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}

	insp, err := r.InspectionService.Start(ctx, hiveID, userID, strings.ToLower(string(input.Type)))
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return inspectionToModel(insp), nil
}

// PauseInspection is the resolver for the pauseInspection field.
func (r *mutationResolver) PauseInspection(ctx context.Context, id string) (*model.Inspection, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	inspID := stringToUUID(id)

	insp, err := r.InspectionService.Pause(ctx, inspID, userID)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return inspectionToModel(insp), nil
}

// ResumeInspection is the resolver for the resumeInspection field.
func (r *mutationResolver) ResumeInspection(ctx context.Context, id string) (*model.Inspection, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	inspID := stringToUUID(id)

	insp, err := r.InspectionService.Resume(ctx, inspID, userID)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return inspectionToModel(insp), nil
}

// CompleteInspection is the resolver for the completeInspection field.
func (r *mutationResolver) CompleteInspection(ctx context.Context, id string) (*model.Inspection, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	inspID := stringToUUID(id)

	insp, err := r.InspectionService.Complete(ctx, inspID, userID)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return inspectionToModel(insp), nil
}

// AddObservation is the resolver for the addObservation field.
func (r *mutationResolver) AddObservation(ctx context.Context, input model.AddObservationInput) (*model.Observation, error) {
	_, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}

	var structuredData []byte
	if input.StructuredData != nil {
		structuredData, _ = json.Marshal(input.StructuredData)
	}
	var rawVoice pgtype.Text
	if input.RawVoiceURL != nil {
		rawVoice = pgtype.Text{String: *input.RawVoiceURL, Valid: true}
	}
	var transcription pgtype.Text
	if input.Transcription != nil {
		transcription = pgtype.Text{String: *input.Transcription, Valid: true}
	}
	var confidence pgtype.Float8
	if input.TranscriptionConfidence != nil {
		confidence = pgtype.Float8{Float64: *input.TranscriptionConfidence, Valid: true}
	}

	obs, err := r.InspectionService.AddObservation(ctx, repository.CreateObservationParams{
		InspectionID:            stringToUUID(input.InspectionID),
		ObservationType:         strings.ToLower(string(input.ObservationType)),
		StructuredData:          structuredData,
		RawVoiceUrl:             rawVoice,
		Transcription:           transcription,
		TranscriptionConfidence: confidence,
	})
	if err != nil {
		return nil, err
	}
	return observationToModel(obs), nil
}

// Inspections is the resolver for the inspections field.
func (r *queryResolver) Inspections(ctx context.Context, hiveID *string, limit *int, offset *int) ([]*model.Inspection, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}

	l := int32(20)
	o := int32(0)
	if limit != nil {
		l = int32(*limit)
	}
	if offset != nil {
		o = int32(*offset)
	}

	var inspections []repository.Inspection
	if hiveID != nil {
		inspections, err = r.InspectionService.ListByHive(ctx, stringToUUID(*hiveID), l, o)
	} else {
		inspections, err = r.InspectionService.ListByUser(ctx, stringToUUID(uid), l, o)
	}
	if err != nil {
		return nil, err
	}

	result := make([]*model.Inspection, len(inspections))
	for i, insp := range inspections {
		result[i] = inspectionToModel(insp)
	}
	return result, nil
}

// Inspection is the resolver for the inspection field.
func (r *queryResolver) Inspection(ctx context.Context, id string) (*model.Inspection, error) {
	insp, err := r.InspectionService.GetByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, domain.NotFoundError(ctx, "inspection")
	}
	return inspectionToModel(insp), nil
}
