package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/broodly/api/graph/model"
)

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, hiveID *string, limit *int, offset *int) ([]*model.Recommendation, error) {
	panic(fmt.Errorf("not implemented: Recommendations - recommendations"))
}
