package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
)

// Recommendations is the resolver for the recommendations field.
// TODO: implement full recommendation resolver once RecommendationService is wired up.
func (r *queryResolver) Recommendations(ctx context.Context, hiveID *string, limit *int, offset *int) ([]*model.Recommendation, error) {
	_, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	return []*model.Recommendation{}, nil
}
