package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
)

// DeferTask is the resolver for the deferTask field.
func (r *mutationResolver) DeferTask(ctx context.Context, id string, input *model.DeferTaskInput) (*model.Task, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	taskID := stringToUUID(id)

	var reason *string
	if input != nil && input.Reason != nil {
		reason = input.Reason
	}

	task, err := r.PlanningService.DeferTask(ctx, taskID, userID, reason)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return taskToModel(task), nil
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, id string) (*model.Task, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)
	taskID := stringToUUID(id)

	task, err := r.PlanningService.CompleteTask(ctx, taskID, userID)
	if err != nil {
		if domErr, ok := err.(*domain.DomainError); ok {
			return nil, domain.ToGraphQLError(ctx, domErr)
		}
		return nil, err
	}
	return taskToModel(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, apiaryID *string, hiveID *string, status *model.TaskStatus, limit *int, offset *int) ([]*model.Task, error) {
	uid, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}
	userID := stringToUUID(uid)

	l := int32(20)
	o := int32(0)
	if limit != nil {
		l = int32(*limit)
	}
	if offset != nil {
		o = int32(*offset)
	}

	var statusFilter *string
	if status != nil {
		s := strings.ToLower(string(*status))
		statusFilter = &s
	}

	tasks, err := r.PlanningService.ListTasks(ctx, userID, statusFilter, l, o)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Task, len(tasks))
	for i, t := range tasks {
		result[i] = taskToModel(t)
	}
	return result, nil
}
