package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/broodly/api/graph/model"
	"github.com/broodly/api/internal/auth"
	"github.com/broodly/api/internal/domain"
	"github.com/broodly/api/internal/repository"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	firebaseUID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, domain.ForbiddenError(ctx)
	}

	// Try to find existing user
	user, err := r.Queries.GetUserByFirebaseUID(ctx, firebaseUID)
	if err == nil {
		return userToModel(user), nil
	}

	// User not found — create on first login (upsert)
	email := auth.EmailFromContext(ctx)
	displayName := strings.Split(email, "@")[0]

	user, err = r.Queries.CreateUser(ctx, repository.CreateUserParams{
		FirebaseUid:     firebaseUID,
		Email:           email,
		DisplayName:     displayName,
		ExperienceLevel: "newbie",
		Region:          "",
	})
	if err != nil {
		return nil, err
	}
	return userToModel(user), nil
}
