// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apiaries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApiariesByUser = `-- name: CountApiariesByUser :one
SELECT COUNT(*) FROM apiaries WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountApiariesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApiariesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiary = `-- name: CreateApiary :one
INSERT INTO apiaries (user_id, name, latitude, longitude, region, elevation_offset, bloom_offset)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, latitude, longitude, region, elevation_offset, bloom_offset, created_at, updated_at, deleted_at
`

type CreateApiaryParams struct {
	UserID          pgtype.UUID   `json:"user_id"`
	Name            string        `json:"name"`
	Latitude        pgtype.Float8 `json:"latitude"`
	Longitude       pgtype.Float8 `json:"longitude"`
	Region          string        `json:"region"`
	ElevationOffset float64       `json:"elevation_offset"`
	BloomOffset     int32         `json:"bloom_offset"`
}

func (q *Queries) CreateApiary(ctx context.Context, arg CreateApiaryParams) (Apiary, error) {
	row := q.db.QueryRow(ctx, createApiary,
		arg.UserID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.Region,
		arg.ElevationOffset,
		arg.BloomOffset,
	)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Region,
		&i.ElevationOffset,
		&i.BloomOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteApiary = `-- name: DeleteApiary :exec
DELETE FROM apiaries WHERE id = $1 AND user_id = $2
`

type DeleteApiaryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteApiary(ctx context.Context, arg DeleteApiaryParams) error {
	_, err := q.db.Exec(ctx, deleteApiary, arg.ID, arg.UserID)
	return err
}

const getApiaryByID = `-- name: GetApiaryByID :one
SELECT id, user_id, name, latitude, longitude, region, elevation_offset, bloom_offset, created_at, updated_at, deleted_at FROM apiaries WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetApiaryByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetApiaryByID(ctx context.Context, arg GetApiaryByIDParams) (Apiary, error) {
	row := q.db.QueryRow(ctx, getApiaryByID, arg.ID, arg.UserID)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Region,
		&i.ElevationOffset,
		&i.BloomOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listApiariesByUser = `-- name: ListApiariesByUser :many
SELECT id, user_id, name, latitude, longitude, region, elevation_offset, bloom_offset, created_at, updated_at, deleted_at FROM apiaries WHERE user_id = $1 AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListApiariesByUser(ctx context.Context, userID pgtype.UUID) ([]Apiary, error) {
	rows, err := q.db.Query(ctx, listApiariesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Apiary
	for rows.Next() {
		var i Apiary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.Region,
			&i.ElevationOffset,
			&i.BloomOffset,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteApiary = `-- name: SoftDeleteApiary :exec
UPDATE apiaries SET deleted_at = NOW() WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteApiaryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteApiary(ctx context.Context, arg SoftDeleteApiaryParams) error {
	_, err := q.db.Exec(ctx, softDeleteApiary, arg.ID, arg.UserID)
	return err
}

const updateApiary = `-- name: UpdateApiary :one
UPDATE apiaries SET name = $2, latitude = $3, longitude = $4, region = $5, elevation_offset = $6, bloom_offset = $7, updated_at = NOW()
WHERE id = $1 AND user_id = $8 AND deleted_at IS NULL RETURNING id, user_id, name, latitude, longitude, region, elevation_offset, bloom_offset, created_at, updated_at, deleted_at
`

type UpdateApiaryParams struct {
	ID              pgtype.UUID   `json:"id"`
	Name            string        `json:"name"`
	Latitude        pgtype.Float8 `json:"latitude"`
	Longitude       pgtype.Float8 `json:"longitude"`
	Region          string        `json:"region"`
	ElevationOffset float64       `json:"elevation_offset"`
	BloomOffset     int32         `json:"bloom_offset"`
	UserID          pgtype.UUID   `json:"user_id"`
}

func (q *Queries) UpdateApiary(ctx context.Context, arg UpdateApiaryParams) (Apiary, error) {
	row := q.db.QueryRow(ctx, updateApiary,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.Region,
		arg.ElevationOffset,
		arg.BloomOffset,
		arg.UserID,
	)
	var i Apiary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.Region,
		&i.ElevationOffset,
		&i.BloomOffset,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
