// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hives.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHive = `-- name: CreateHive :one
INSERT INTO hives (apiary_id, name, type, status, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, apiary_id, name, type, status, notes, created_at, updated_at
`

type CreateHiveParams struct {
	ApiaryID pgtype.UUID `json:"apiary_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	Status   string      `json:"status"`
	Notes    string      `json:"notes"`
}

func (q *Queries) CreateHive(ctx context.Context, arg CreateHiveParams) (Hive, error) {
	row := q.db.QueryRow(ctx, createHive,
		arg.ApiaryID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Notes,
	)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHive = `-- name: DeleteHive :exec
DELETE FROM hives WHERE id = $1 AND apiary_id IN (SELECT id FROM apiaries WHERE user_id = $2)
`

type DeleteHiveParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteHive(ctx context.Context, arg DeleteHiveParams) error {
	_, err := q.db.Exec(ctx, deleteHive, arg.ID, arg.UserID)
	return err
}

const getHiveByID = `-- name: GetHiveByID :one
SELECT h.id, h.apiary_id, h.name, h.type, h.status, h.notes, h.created_at, h.updated_at
FROM hives h
JOIN apiaries a ON h.apiary_id = a.id
WHERE h.id = $1 AND a.user_id = $2
`

type GetHiveByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetHiveByID(ctx context.Context, arg GetHiveByIDParams) (Hive, error) {
	row := q.db.QueryRow(ctx, getHiveByID, arg.ID, arg.UserID)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHivesByApiary = `-- name: ListHivesByApiary :many
SELECT id, apiary_id, name, type, status, notes, created_at, updated_at FROM hives WHERE apiary_id = $1 ORDER BY name
`

func (q *Queries) ListHivesByApiary(ctx context.Context, apiaryID pgtype.UUID) ([]Hive, error) {
	rows, err := q.db.Query(ctx, listHivesByApiary, apiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hive
	for rows.Next() {
		var i Hive
		if err := rows.Scan(
			&i.ID,
			&i.ApiaryID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHive = `-- name: UpdateHive :one
UPDATE hives SET name = $2, type = $3, status = $4, notes = $5, updated_at = NOW()
WHERE id = $1 AND apiary_id IN (SELECT id FROM apiaries WHERE user_id = $6)
RETURNING id, apiary_id, name, type, status, notes, created_at, updated_at
`

type UpdateHiveParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
	Notes  string      `json:"notes"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateHive(ctx context.Context, arg UpdateHiveParams) (Hive, error) {
	row := q.db.QueryRow(ctx, updateHive,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Notes,
		arg.UserID,
	)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
