// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hives.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHivesByUser = `-- name: CountHivesByUser :one
SELECT COUNT(*) FROM hives h
JOIN apiaries a ON h.apiary_id = a.id
WHERE a.user_id = $1 AND h.deleted_at IS NULL AND a.deleted_at IS NULL
`

func (q *Queries) CountHivesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHivesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHive = `-- name: CreateHive :one
INSERT INTO hives (apiary_id, name, type, status, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, apiary_id, name, type, status, notes, created_at, updated_at, deleted_at
`

type CreateHiveParams struct {
	ApiaryID pgtype.UUID `json:"apiary_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	Status   string      `json:"status"`
	Notes    string      `json:"notes"`
}

func (q *Queries) CreateHive(ctx context.Context, arg CreateHiveParams) (Hive, error) {
	row := q.db.QueryRow(ctx, createHive,
		arg.ApiaryID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Notes,
	)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteHive = `-- name: DeleteHive :exec
DELETE FROM hives WHERE id = $1
`

func (q *Queries) DeleteHive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHive, id)
	return err
}

const getHiveByID = `-- name: GetHiveByID :one
SELECT id, apiary_id, name, type, status, notes, created_at, updated_at, deleted_at FROM hives WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHiveByID(ctx context.Context, id pgtype.UUID) (Hive, error) {
	row := q.db.QueryRow(ctx, getHiveByID, id)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHiveByIDAndUser = `-- name: GetHiveByIDAndUser :one
SELECT h.id, h.apiary_id, h.name, h.type, h.status, h.notes, h.created_at, h.updated_at, h.deleted_at FROM hives h
JOIN apiaries a ON h.apiary_id = a.id
WHERE h.id = $1 AND a.user_id = $2 AND h.deleted_at IS NULL AND a.deleted_at IS NULL
`

type GetHiveByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetHiveByIDAndUser(ctx context.Context, arg GetHiveByIDAndUserParams) (Hive, error) {
	row := q.db.QueryRow(ctx, getHiveByIDAndUser, arg.ID, arg.UserID)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listHivesByApiary = `-- name: ListHivesByApiary :many
SELECT id, apiary_id, name, type, status, notes, created_at, updated_at, deleted_at FROM hives WHERE apiary_id = $1 AND deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListHivesByApiary(ctx context.Context, apiaryID pgtype.UUID) ([]Hive, error) {
	rows, err := q.db.Query(ctx, listHivesByApiary, apiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hive
	for rows.Next() {
		var i Hive
		if err := rows.Scan(
			&i.ID,
			&i.ApiaryID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHivesByApiaryIDs = `-- name: ListHivesByApiaryIDs :many
SELECT id, apiary_id, name, type, status, notes, created_at, updated_at, deleted_at FROM hives WHERE apiary_id = ANY($1::uuid[]) AND deleted_at IS NULL ORDER BY apiary_id, name
`

func (q *Queries) ListHivesByApiaryIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Hive, error) {
	rows, err := q.db.Query(ctx, listHivesByApiaryIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hive
	for rows.Next() {
		var i Hive
		if err := rows.Scan(
			&i.ID,
			&i.ApiaryID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteHive = `-- name: SoftDeleteHive :exec
UPDATE hives SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteHive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHive, id)
	return err
}

const softDeleteHivesByApiary = `-- name: SoftDeleteHivesByApiary :exec
UPDATE hives SET deleted_at = NOW() WHERE apiary_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteHivesByApiary(ctx context.Context, apiaryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHivesByApiary, apiaryID)
	return err
}

const updateHive = `-- name: UpdateHive :one
UPDATE hives SET name = $2, type = $3, status = $4, notes = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, apiary_id, name, type, status, notes, created_at, updated_at, deleted_at
`

type UpdateHiveParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
	Notes  string      `json:"notes"`
}

func (q *Queries) UpdateHive(ctx context.Context, arg UpdateHiveParams) (Hive, error) {
	row := q.db.QueryRow(ctx, updateHive,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.Notes,
	)
	var i Hive
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
