// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inspections.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeInspection = `-- name: CompleteInspection :one
UPDATE inspections SET status = 'completed', completed_at = NOW(), notes = $2
WHERE id = $1 RETURNING id, hive_id, user_id, type, status, started_at, completed_at, notes, created_at
`

type CompleteInspectionParams struct {
	ID    pgtype.UUID `json:"id"`
	Notes string      `json:"notes"`
}

func (q *Queries) CompleteInspection(ctx context.Context, arg CompleteInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, completeInspection, arg.ID, arg.Notes)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createInspection = `-- name: CreateInspection :one
INSERT INTO inspections (hive_id, user_id, type, status, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, hive_id, user_id, type, status, started_at, completed_at, notes, created_at
`

type CreateInspectionParams struct {
	HiveID pgtype.UUID `json:"hive_id"`
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
	Notes  string      `json:"notes"`
}

func (q *Queries) CreateInspection(ctx context.Context, arg CreateInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, createInspection,
		arg.HiveID,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Notes,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (observation_id, storage_path, content_type)
VALUES ($1, $2, $3)
RETURNING id, observation_id, storage_path, content_type, analysis_status, analysis_result, created_at
`

type CreateMediaParams struct {
	ObservationID pgtype.UUID `json:"observation_id"`
	StoragePath   string      `json:"storage_path"`
	ContentType   string      `json:"content_type"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia, arg.ObservationID, arg.StoragePath, arg.ContentType)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.StoragePath,
		&i.ContentType,
		&i.AnalysisStatus,
		&i.AnalysisResult,
		&i.CreatedAt,
	)
	return i, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (inspection_id, sequence_order, observation_type, structured_data, raw_voice_url, transcription, transcription_confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, inspection_id, sequence_order, observation_type, structured_data, raw_voice_url, transcription, transcription_confidence, created_at
`

type CreateObservationParams struct {
	InspectionID            pgtype.UUID   `json:"inspection_id"`
	SequenceOrder           int32         `json:"sequence_order"`
	ObservationType         string        `json:"observation_type"`
	StructuredData          []byte        `json:"structured_data"`
	RawVoiceUrl             pgtype.Text   `json:"raw_voice_url"`
	Transcription           pgtype.Text   `json:"transcription"`
	TranscriptionConfidence pgtype.Float8 `json:"transcription_confidence"`
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.InspectionID,
		arg.SequenceOrder,
		arg.ObservationType,
		arg.StructuredData,
		arg.RawVoiceUrl,
		arg.Transcription,
		arg.TranscriptionConfidence,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.InspectionID,
		&i.SequenceOrder,
		&i.ObservationType,
		&i.StructuredData,
		&i.RawVoiceUrl,
		&i.Transcription,
		&i.TranscriptionConfidence,
		&i.CreatedAt,
	)
	return i, err
}

const getInspectionByID = `-- name: GetInspectionByID :one
SELECT id, hive_id, user_id, type, status, started_at, completed_at, notes, created_at FROM inspections WHERE id = $1
`

func (q *Queries) GetInspectionByID(ctx context.Context, id pgtype.UUID) (Inspection, error) {
	row := q.db.QueryRow(ctx, getInspectionByID, id)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listInspectionsByHive = `-- name: ListInspectionsByHive :many
SELECT id, hive_id, user_id, type, status, started_at, completed_at, notes, created_at FROM inspections WHERE hive_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListInspectionsByHive(ctx context.Context, hiveID pgtype.UUID) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByHive, hiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inspection
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByObservation = `-- name: ListMediaByObservation :many
SELECT id, observation_id, storage_path, content_type, analysis_status, analysis_result, created_at FROM media WHERE observation_id = $1
`

func (q *Queries) ListMediaByObservation(ctx context.Context, observationID pgtype.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByObservation, observationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.ObservationID,
			&i.StoragePath,
			&i.ContentType,
			&i.AnalysisStatus,
			&i.AnalysisResult,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByInspection = `-- name: ListObservationsByInspection :many
SELECT id, inspection_id, sequence_order, observation_type, structured_data, raw_voice_url, transcription, transcription_confidence, created_at FROM observations WHERE inspection_id = $1 ORDER BY sequence_order
`

func (q *Queries) ListObservationsByInspection(ctx context.Context, inspectionID pgtype.UUID) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByInspection, inspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.InspectionID,
			&i.SequenceOrder,
			&i.ObservationType,
			&i.StructuredData,
			&i.RawVoiceUrl,
			&i.Transcription,
			&i.TranscriptionConfidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseInspection = `-- name: PauseInspection :one
UPDATE inspections SET status = 'paused' WHERE id = $1 RETURNING id, hive_id, user_id, type, status, started_at, completed_at, notes, created_at
`

func (q *Queries) PauseInspection(ctx context.Context, id pgtype.UUID) (Inspection, error) {
	row := q.db.QueryRow(ctx, pauseInspection, id)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateMediaAnalysis = `-- name: UpdateMediaAnalysis :one
UPDATE media SET analysis_status = $2, analysis_result = $3
WHERE id = $1 RETURNING id, observation_id, storage_path, content_type, analysis_status, analysis_result, created_at
`

type UpdateMediaAnalysisParams struct {
	ID             pgtype.UUID `json:"id"`
	AnalysisStatus string      `json:"analysis_status"`
	AnalysisResult []byte      `json:"analysis_result"`
}

func (q *Queries) UpdateMediaAnalysis(ctx context.Context, arg UpdateMediaAnalysisParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaAnalysis, arg.ID, arg.AnalysisStatus, arg.AnalysisResult)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.StoragePath,
		&i.ContentType,
		&i.AnalysisStatus,
		&i.AnalysisResult,
		&i.CreatedAt,
	)
	return i, err
}
