// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (user_id, provider, credentials_ref, hive_mappings)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, credentials_ref, status, hive_mappings, last_sync_at, created_at
`

type CreateIntegrationParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Provider       string      `json:"provider"`
	CredentialsRef string      `json:"credentials_ref"`
	HiveMappings   []byte      `json:"hive_mappings"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.UserID,
		arg.Provider,
		arg.CredentialsRef,
		arg.HiveMappings,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.CredentialsRef,
		&i.Status,
		&i.HiveMappings,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTelemetryReading = `-- name: CreateTelemetryReading :exec
INSERT INTO telemetry_readings (integration_id, hive_id, reading_type, value, unit, recorded_at, plausibility_status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTelemetryReadingParams struct {
	IntegrationID      pgtype.UUID        `json:"integration_id"`
	HiveID             pgtype.UUID        `json:"hive_id"`
	ReadingType        string             `json:"reading_type"`
	Value              float64            `json:"value"`
	Unit               string             `json:"unit"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
	PlausibilityStatus string             `json:"plausibility_status"`
}

func (q *Queries) CreateTelemetryReading(ctx context.Context, arg CreateTelemetryReadingParams) error {
	_, err := q.db.Exec(ctx, createTelemetryReading,
		arg.IntegrationID,
		arg.HiveID,
		arg.ReadingType,
		arg.Value,
		arg.Unit,
		arg.RecordedAt,
		arg.PlausibilityStatus,
	)
	return err
}

const getExternalContext = `-- name: GetExternalContext :one
SELECT id, apiary_id, source_type, data, fetched_at, staleness_threshold_hours FROM external_context WHERE apiary_id = $1 AND source_type = $2 ORDER BY fetched_at DESC LIMIT 1
`

type GetExternalContextParams struct {
	ApiaryID   pgtype.UUID `json:"apiary_id"`
	SourceType string      `json:"source_type"`
}

func (q *Queries) GetExternalContext(ctx context.Context, arg GetExternalContextParams) (ExternalContext, error) {
	row := q.db.QueryRow(ctx, getExternalContext, arg.ApiaryID, arg.SourceType)
	var i ExternalContext
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.SourceType,
		&i.Data,
		&i.FetchedAt,
		&i.StalenessThresholdHours,
	)
	return i, err
}

const listIntegrationsByUser = `-- name: ListIntegrationsByUser :many
SELECT id, user_id, provider, credentials_ref, status, hive_mappings, last_sync_at, created_at FROM integrations WHERE user_id = $1
`

func (q *Queries) ListIntegrationsByUser(ctx context.Context, userID pgtype.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.CredentialsRef,
			&i.Status,
			&i.HiveMappings,
			&i.LastSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleExternalContext = `-- name: ListStaleExternalContext :many
SELECT id, apiary_id, source_type, data, fetched_at, staleness_threshold_hours FROM external_context
WHERE fetched_at < NOW() - (staleness_threshold_hours || ' hours')::INTERVAL
`

func (q *Queries) ListStaleExternalContext(ctx context.Context) ([]ExternalContext, error) {
	rows, err := q.db.Query(ctx, listStaleExternalContext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalContext
	for rows.Next() {
		var i ExternalContext
		if err := rows.Scan(
			&i.ID,
			&i.ApiaryID,
			&i.SourceType,
			&i.Data,
			&i.FetchedAt,
			&i.StalenessThresholdHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelemetryByHive = `-- name: ListTelemetryByHive :many
SELECT id, integration_id, hive_id, reading_type, value, unit, recorded_at, ingested_at, plausibility_status FROM telemetry_readings WHERE hive_id = $1 AND recorded_at >= $2 ORDER BY recorded_at
`

type ListTelemetryByHiveParams struct {
	HiveID     pgtype.UUID        `json:"hive_id"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) ListTelemetryByHive(ctx context.Context, arg ListTelemetryByHiveParams) ([]TelemetryReading, error) {
	rows, err := q.db.Query(ctx, listTelemetryByHive, arg.HiveID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryReading
	for rows.Next() {
		var i TelemetryReading
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.HiveID,
			&i.ReadingType,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
			&i.IngestedAt,
			&i.PlausibilityStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationSync = `-- name: UpdateIntegrationSync :one
UPDATE integrations SET last_sync_at = NOW(), status = $2
WHERE id = $1 RETURNING id, user_id, provider, credentials_ref, status, hive_mappings, last_sync_at, created_at
`

type UpdateIntegrationSyncParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateIntegrationSync(ctx context.Context, arg UpdateIntegrationSyncParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationSync, arg.ID, arg.Status)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.CredentialsRef,
		&i.Status,
		&i.HiveMappings,
		&i.LastSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExternalContext = `-- name: UpsertExternalContext :one
INSERT INTO external_context (apiary_id, source_type, data, fetched_at, staleness_threshold_hours)
VALUES ($1, $2, $3, NOW(), $4)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, fetched_at = NOW()
RETURNING id, apiary_id, source_type, data, fetched_at, staleness_threshold_hours
`

type UpsertExternalContextParams struct {
	ApiaryID                pgtype.UUID `json:"apiary_id"`
	SourceType              string      `json:"source_type"`
	Data                    []byte      `json:"data"`
	StalenessThresholdHours int32       `json:"staleness_threshold_hours"`
}

func (q *Queries) UpsertExternalContext(ctx context.Context, arg UpsertExternalContextParams) (ExternalContext, error) {
	row := q.db.QueryRow(ctx, upsertExternalContext,
		arg.ApiaryID,
		arg.SourceType,
		arg.Data,
		arg.StalenessThresholdHours,
	)
	var i ExternalContext
	err := row.Scan(
		&i.ID,
		&i.ApiaryID,
		&i.SourceType,
		&i.Data,
		&i.FetchedAt,
		&i.StalenessThresholdHours,
	)
	return i, err
}
