// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Apiary struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	Region          string             `json:"region"`
	ElevationOffset float64            `json:"elevation_offset"`
	BloomOffset     int32              `json:"bloom_offset"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID             pgtype.UUID        `json:"id"`
	EventType      string             `json:"event_type"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	PayloadVersion int32              `json:"payload_version"`
	Payload        []byte             `json:"payload"`
}

type ExternalContext struct {
	ID                      pgtype.UUID        `json:"id"`
	ApiaryID                pgtype.UUID        `json:"apiary_id"`
	SourceType              string             `json:"source_type"`
	Data                    []byte             `json:"data"`
	FetchedAt               pgtype.Timestamptz `json:"fetched_at"`
	StalenessThresholdHours int32              `json:"staleness_threshold_hours"`
}

type Hive struct {
	ID        pgtype.UUID        `json:"id"`
	ApiaryID  pgtype.UUID        `json:"apiary_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Status    string             `json:"status"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Inspection struct {
	ID          pgtype.UUID        `json:"id"`
	HiveID      pgtype.UUID        `json:"hive_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Integration struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       string             `json:"provider"`
	CredentialsRef string             `json:"credentials_ref"`
	Status         string             `json:"status"`
	HiveMappings   []byte             `json:"hive_mappings"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Medium struct {
	ID             pgtype.UUID        `json:"id"`
	ObservationID  pgtype.UUID        `json:"observation_id"`
	StoragePath    string             `json:"storage_path"`
	ContentType    string             `json:"content_type"`
	AnalysisStatus string             `json:"analysis_status"`
	AnalysisResult []byte             `json:"analysis_result"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	ID                     pgtype.UUID        `json:"id"`
	UserID                 pgtype.UUID        `json:"user_id"`
	ApiaryID               pgtype.UUID        `json:"apiary_id"`
	SensitivityLevel       string             `json:"sensitivity_level"`
	SuppressionWindowStart pgtype.Time        `json:"suppression_window_start"`
	SuppressionWindowEnd   pgtype.Time        `json:"suppression_window_end"`
	EscalationEnabled      bool               `json:"escalation_enabled"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Observation struct {
	ID                      pgtype.UUID        `json:"id"`
	InspectionID            pgtype.UUID        `json:"inspection_id"`
	SequenceOrder           int32              `json:"sequence_order"`
	ObservationType         string             `json:"observation_type"`
	StructuredData          []byte             `json:"structured_data"`
	RawVoiceUrl             pgtype.Text        `json:"raw_voice_url"`
	Transcription           pgtype.Text        `json:"transcription"`
	TranscriptionConfidence pgtype.Float8      `json:"transcription_confidence"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type Recommendation struct {
	ID              pgtype.UUID        `json:"id"`
	HiveID          pgtype.UUID        `json:"hive_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Action          string             `json:"action"`
	Rationale       string             `json:"rationale"`
	ConfidenceLevel float64            `json:"confidence_level"`
	ConfidenceType  string             `json:"confidence_type"`
	FallbackAction  string             `json:"fallback_action"`
	EvidenceContext []byte             `json:"evidence_context"`
	SourceVersions  []byte             `json:"source_versions"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type SkillProgression struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CurrentLevel        string             `json:"current_level"`
	MilestonesCompleted []byte             `json:"milestones_completed"`
	TotalInspections    int32              `json:"total_inspections"`
	LastAssessedAt      pgtype.Timestamptz `json:"last_assessed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID               pgtype.UUID        `json:"id"`
	RecommendationID pgtype.UUID        `json:"recommendation_id"`
	HiveID           pgtype.UUID        `json:"hive_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Title            string             `json:"title"`
	Priority         string             `json:"priority"`
	Status           string             `json:"status"`
	DueDate          pgtype.Date        `json:"due_date"`
	DeferredReason   pgtype.Text        `json:"deferred_reason"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TelemetryReading struct {
	ID                 pgtype.UUID        `json:"id"`
	IntegrationID      pgtype.UUID        `json:"integration_id"`
	HiveID             pgtype.UUID        `json:"hive_id"`
	ReadingType        string             `json:"reading_type"`
	Value              float64            `json:"value"`
	Unit               string             `json:"unit"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
	IngestedAt         pgtype.Timestamptz `json:"ingested_at"`
	PlausibilityStatus string             `json:"plausibility_status"`
}

type TreatmentRegistry struct {
	ID            pgtype.UUID        `json:"id"`
	TreatmentName string             `json:"treatment_name"`
	Region        string             `json:"region"`
	LegalStatus   string             `json:"legal_status"`
	Notes         string             `json:"notes"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	FirebaseUid     string             `json:"firebase_uid"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	ExperienceLevel string             `json:"experience_level"`
	Region          string             `json:"region"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserFeedback struct {
	ID               pgtype.UUID        `json:"id"`
	RecommendationID pgtype.UUID        `json:"recommendation_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OutcomeReport    string             `json:"outcome_report"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
