// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteInspection(ctx context.Context, arg CompleteInspectionParams) (Inspection, error)
	CreateApiary(ctx context.Context, arg CreateApiaryParams) (Apiary, error)
	CreateHive(ctx context.Context, arg CreateHiveParams) (Hive, error)
	CreateInspection(ctx context.Context, arg CreateInspectionParams) (Inspection, error)
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error)
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTelemetryReading(ctx context.Context, arg CreateTelemetryReadingParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserFeedback(ctx context.Context, arg CreateUserFeedbackParams) (UserFeedback, error)
	DeleteApiary(ctx context.Context, arg DeleteApiaryParams) error
	DeleteHive(ctx context.Context, id pgtype.UUID) error
	GetApiaryByID(ctx context.Context, arg GetApiaryByIDParams) (Apiary, error)
	GetExternalContext(ctx context.Context, arg GetExternalContextParams) (ExternalContext, error)
	GetHiveByID(ctx context.Context, id pgtype.UUID) (Hive, error)
	GetInspectionByID(ctx context.Context, id pgtype.UUID) (Inspection, error)
	GetNotificationPreferences(ctx context.Context, arg GetNotificationPreferencesParams) (NotificationPreference, error)
	GetRecommendationByID(ctx context.Context, id pgtype.UUID) (Recommendation, error)
	GetSkillProgression(ctx context.Context, userID pgtype.UUID) (SkillProgression, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	ListActiveRecommendationsByUser(ctx context.Context, userID pgtype.UUID) ([]Recommendation, error)
	ListAllTreatments(ctx context.Context) ([]TreatmentRegistry, error)
	ListApiariesByUser(ctx context.Context, userID pgtype.UUID) ([]Apiary, error)
	ListAuditEventsByTenant(ctx context.Context, arg ListAuditEventsByTenantParams) ([]AuditEvent, error)
	ListHivesByApiary(ctx context.Context, apiaryID pgtype.UUID) ([]Hive, error)
	ListInspectionsByHive(ctx context.Context, hiveID pgtype.UUID) ([]Inspection, error)
	ListIntegrationsByUser(ctx context.Context, userID pgtype.UUID) ([]Integration, error)
	ListMediaByObservation(ctx context.Context, observationID pgtype.UUID) ([]Medium, error)
	ListObservationsByInspection(ctx context.Context, inspectionID pgtype.UUID) ([]Observation, error)
	ListPendingTasksByUser(ctx context.Context, userID pgtype.UUID) ([]Task, error)
	ListRecommendationsByHive(ctx context.Context, hiveID pgtype.UUID) ([]Recommendation, error)
	ListStaleExternalContext(ctx context.Context) ([]ExternalContext, error)
	ListTelemetryByHive(ctx context.Context, arg ListTelemetryByHiveParams) ([]TelemetryReading, error)
	ListTreatmentsByRegion(ctx context.Context, region string) ([]TreatmentRegistry, error)
	PauseInspection(ctx context.Context, id pgtype.UUID) (Inspection, error)
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateApiary(ctx context.Context, arg UpdateApiaryParams) (Apiary, error)
	UpdateHive(ctx context.Context, arg UpdateHiveParams) (Hive, error)
	UpdateIntegrationSync(ctx context.Context, arg UpdateIntegrationSyncParams) (Integration, error)
	UpdateMediaAnalysis(ctx context.Context, arg UpdateMediaAnalysisParams) (Medium, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertExternalContext(ctx context.Context, arg UpsertExternalContextParams) (ExternalContext, error)
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
	UpsertSkillProgression(ctx context.Context, arg UpsertSkillProgressionParams) (SkillProgression, error)
}

var _ Querier = (*Queries)(nil)
