// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO recommendations (hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at
`

type CreateRecommendationParams struct {
	HiveID          pgtype.UUID        `json:"hive_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Action          string             `json:"action"`
	Rationale       string             `json:"rationale"`
	ConfidenceLevel float64            `json:"confidence_level"`
	ConfidenceType  string             `json:"confidence_type"`
	FallbackAction  string             `json:"fallback_action"`
	EvidenceContext []byte             `json:"evidence_context"`
	SourceVersions  []byte             `json:"source_versions"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, createRecommendation,
		arg.HiveID,
		arg.UserID,
		arg.Action,
		arg.Rationale,
		arg.ConfidenceLevel,
		arg.ConfidenceType,
		arg.FallbackAction,
		arg.EvidenceContext,
		arg.SourceVersions,
		arg.ExpiresAt,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Action,
		&i.Rationale,
		&i.ConfidenceLevel,
		&i.ConfidenceType,
		&i.FallbackAction,
		&i.EvidenceContext,
		&i.SourceVersions,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (recommendation_id, hive_id, user_id, title, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at
`

type CreateTaskParams struct {
	RecommendationID pgtype.UUID `json:"recommendation_id"`
	HiveID           pgtype.UUID `json:"hive_id"`
	UserID           pgtype.UUID `json:"user_id"`
	Title            string      `json:"title"`
	Priority         string      `json:"priority"`
	DueDate          pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.RecommendationID,
		arg.HiveID,
		arg.UserID,
		arg.Title,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.HiveID,
		&i.UserID,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.DeferredReason,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserFeedback = `-- name: CreateUserFeedback :one
INSERT INTO user_feedback (recommendation_id, user_id, outcome_report)
VALUES ($1, $2, $3)
RETURNING id, recommendation_id, user_id, outcome_report, created_at
`

type CreateUserFeedbackParams struct {
	RecommendationID pgtype.UUID `json:"recommendation_id"`
	UserID           pgtype.UUID `json:"user_id"`
	OutcomeReport    string      `json:"outcome_report"`
}

func (q *Queries) CreateUserFeedback(ctx context.Context, arg CreateUserFeedbackParams) (UserFeedback, error) {
	row := q.db.QueryRow(ctx, createUserFeedback, arg.RecommendationID, arg.UserID, arg.OutcomeReport)
	var i UserFeedback
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.UserID,
		&i.OutcomeReport,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendationByID = `-- name: GetRecommendationByID :one
SELECT id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at FROM recommendations WHERE id = $1
`

func (q *Queries) GetRecommendationByID(ctx context.Context, id pgtype.UUID) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendationByID, id)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.HiveID,
		&i.UserID,
		&i.Action,
		&i.Rationale,
		&i.ConfidenceLevel,
		&i.ConfidenceType,
		&i.FallbackAction,
		&i.EvidenceContext,
		&i.SourceVersions,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.HiveID,
		&i.UserID,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.DeferredReason,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByIDAndUser = `-- name: GetTaskByIDAndUser :one
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTaskByIDAndUser(ctx context.Context, arg GetTaskByIDAndUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIDAndUser, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.HiveID,
		&i.UserID,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.DeferredReason,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (event_type, actor_id, tenant_id, payload_version, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditEventParams struct {
	EventType      string      `json:"event_type"`
	ActorID        pgtype.UUID `json:"actor_id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	PayloadVersion int32       `json:"payload_version"`
	Payload        []byte      `json:"payload"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.EventType,
		arg.ActorID,
		arg.TenantID,
		arg.PayloadVersion,
		arg.Payload,
	)
	return err
}

const listActiveRecommendationsByUser = `-- name: ListActiveRecommendationsByUser :many
SELECT id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at FROM recommendations WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > NOW()) ORDER BY created_at DESC
`

func (q *Queries) ListActiveRecommendationsByUser(ctx context.Context, userID pgtype.UUID) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listActiveRecommendationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.UserID,
			&i.Action,
			&i.Rationale,
			&i.ConfidenceLevel,
			&i.ConfidenceType,
			&i.FallbackAction,
			&i.EvidenceContext,
			&i.SourceVersions,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByTenant = `-- name: ListAuditEventsByTenant :many
SELECT id, event_type, actor_id, tenant_id, occurred_at, payload_version, payload FROM audit_events WHERE tenant_id = $1 ORDER BY occurred_at DESC LIMIT $2
`

type ListAuditEventsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListAuditEventsByTenant(ctx context.Context, arg ListAuditEventsByTenantParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.TenantID,
			&i.OccurredAt,
			&i.PayloadVersion,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasksByUser = `-- name: ListPendingTasksByUser :many
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE user_id = $1 AND status = 'pending' ORDER BY due_date NULLS LAST, priority
`

func (q *Queries) ListPendingTasksByUser(ctx context.Context, userID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listPendingTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.HiveID,
			&i.UserID,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.DeferredReason,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByHive = `-- name: ListRecommendationsByHive :many
SELECT id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at FROM recommendations WHERE hive_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRecommendationsByHive(ctx context.Context, hiveID pgtype.UUID) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByHive, hiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.UserID,
			&i.Action,
			&i.Rationale,
			&i.ConfidenceLevel,
			&i.ConfidenceType,
			&i.FallbackAction,
			&i.EvidenceContext,
			&i.SourceVersions,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByHivePaginated = `-- name: ListRecommendationsByHivePaginated :many
SELECT id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at FROM recommendations WHERE hive_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRecommendationsByHivePaginatedParams struct {
	HiveID pgtype.UUID `json:"hive_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListRecommendationsByHivePaginated(ctx context.Context, arg ListRecommendationsByHivePaginatedParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByHivePaginated, arg.HiveID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.UserID,
			&i.Action,
			&i.Rationale,
			&i.ConfidenceLevel,
			&i.ConfidenceType,
			&i.FallbackAction,
			&i.EvidenceContext,
			&i.SourceVersions,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByUser = `-- name: ListRecommendationsByUser :many
SELECT id, hive_id, user_id, action, rationale, confidence_level, confidence_type, fallback_action, evidence_context, source_versions, created_at, expires_at FROM recommendations WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRecommendationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListRecommendationsByUser(ctx context.Context, arg ListRecommendationsByUserParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.UserID,
			&i.Action,
			&i.Rationale,
			&i.ConfidenceLevel,
			&i.ConfidenceType,
			&i.FallbackAction,
			&i.EvidenceContext,
			&i.SourceVersions,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByHive = `-- name: ListTasksByHive :many
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE hive_id = $1 ORDER BY due_date NULLS LAST, priority LIMIT $2 OFFSET $3
`

type ListTasksByHiveParams struct {
	HiveID pgtype.UUID `json:"hive_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTasksByHive(ctx context.Context, arg ListTasksByHiveParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByHive, arg.HiveID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.HiveID,
			&i.UserID,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.DeferredReason,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE user_id = $1 ORDER BY due_date NULLS LAST, priority LIMIT $2 OFFSET $3
`

type ListTasksByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.HiveID,
			&i.UserID,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.DeferredReason,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUserAndStatus = `-- name: ListTasksByUserAndStatus :many
SELECT id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at FROM tasks WHERE user_id = $1 AND status = $2 ORDER BY due_date NULLS LAST, priority LIMIT $3 OFFSET $4
`

type ListTasksByUserAndStatusParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTasksByUserAndStatus(ctx context.Context, arg ListTasksByUserAndStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RecommendationID,
			&i.HiveID,
			&i.UserID,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.DeferredReason,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2, deferred_reason = $3, completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE NULL END
WHERE id = $1 RETURNING id, recommendation_id, hive_id, user_id, title, priority, status, due_date, deferred_reason, completed_at, created_at
`

type UpdateTaskStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	DeferredReason pgtype.Text `json:"deferred_reason"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status, arg.DeferredReason)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RecommendationID,
		&i.HiveID,
		&i.UserID,
		&i.Title,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.DeferredReason,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
