// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill_notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT id, user_id, apiary_id, sensitivity_level, suppression_window_start, suppression_window_end, escalation_enabled, created_at, updated_at FROM notification_preferences WHERE user_id = $1 AND apiary_id IS NOT DISTINCT FROM $2
`

type GetNotificationPreferencesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ApiaryID pgtype.UUID `json:"apiary_id"`
}

func (q *Queries) GetNotificationPreferences(ctx context.Context, arg GetNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, arg.UserID, arg.ApiaryID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiaryID,
		&i.SensitivityLevel,
		&i.SuppressionWindowStart,
		&i.SuppressionWindowEnd,
		&i.EscalationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillProgression = `-- name: GetSkillProgression :one
SELECT id, user_id, current_level, milestones_completed, total_inspections, last_assessed_at, created_at, updated_at FROM skill_progression WHERE user_id = $1
`

func (q *Queries) GetSkillProgression(ctx context.Context, userID pgtype.UUID) (SkillProgression, error) {
	row := q.db.QueryRow(ctx, getSkillProgression, userID)
	var i SkillProgression
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentLevel,
		&i.MilestonesCompleted,
		&i.TotalInspections,
		&i.LastAssessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTreatments = `-- name: ListAllTreatments :many
SELECT id, treatment_name, region, legal_status, notes, updated_at FROM treatment_registry ORDER BY region, treatment_name
`

func (q *Queries) ListAllTreatments(ctx context.Context) ([]TreatmentRegistry, error) {
	rows, err := q.db.Query(ctx, listAllTreatments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TreatmentRegistry
	for rows.Next() {
		var i TreatmentRegistry
		if err := rows.Scan(
			&i.ID,
			&i.TreatmentName,
			&i.Region,
			&i.LegalStatus,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreatmentsByRegion = `-- name: ListTreatmentsByRegion :many
SELECT id, treatment_name, region, legal_status, notes, updated_at FROM treatment_registry WHERE region = $1 ORDER BY treatment_name
`

func (q *Queries) ListTreatmentsByRegion(ctx context.Context, region string) ([]TreatmentRegistry, error) {
	rows, err := q.db.Query(ctx, listTreatmentsByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TreatmentRegistry
	for rows.Next() {
		var i TreatmentRegistry
		if err := rows.Scan(
			&i.ID,
			&i.TreatmentName,
			&i.Region,
			&i.LegalStatus,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, apiary_id, sensitivity_level, suppression_window_start, suppression_window_end, escalation_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, apiary_id) DO UPDATE SET sensitivity_level = EXCLUDED.sensitivity_level, suppression_window_start = EXCLUDED.suppression_window_start, suppression_window_end = EXCLUDED.suppression_window_end, escalation_enabled = EXCLUDED.escalation_enabled, updated_at = NOW()
RETURNING id, user_id, apiary_id, sensitivity_level, suppression_window_start, suppression_window_end, escalation_enabled, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID                 pgtype.UUID `json:"user_id"`
	ApiaryID               pgtype.UUID `json:"apiary_id"`
	SensitivityLevel       string      `json:"sensitivity_level"`
	SuppressionWindowStart pgtype.Time `json:"suppression_window_start"`
	SuppressionWindowEnd   pgtype.Time `json:"suppression_window_end"`
	EscalationEnabled      bool        `json:"escalation_enabled"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.ApiaryID,
		arg.SensitivityLevel,
		arg.SuppressionWindowStart,
		arg.SuppressionWindowEnd,
		arg.EscalationEnabled,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiaryID,
		&i.SensitivityLevel,
		&i.SuppressionWindowStart,
		&i.SuppressionWindowEnd,
		&i.EscalationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSkillProgression = `-- name: UpsertSkillProgression :one
INSERT INTO skill_progression (user_id, current_level, milestones_completed, total_inspections, last_assessed_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET current_level = EXCLUDED.current_level, milestones_completed = EXCLUDED.milestones_completed, total_inspections = EXCLUDED.total_inspections, last_assessed_at = NOW(), updated_at = NOW()
RETURNING id, user_id, current_level, milestones_completed, total_inspections, last_assessed_at, created_at, updated_at
`

type UpsertSkillProgressionParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	CurrentLevel        string      `json:"current_level"`
	MilestonesCompleted []byte      `json:"milestones_completed"`
	TotalInspections    int32       `json:"total_inspections"`
}

func (q *Queries) UpsertSkillProgression(ctx context.Context, arg UpsertSkillProgressionParams) (SkillProgression, error) {
	row := q.db.QueryRow(ctx, upsertSkillProgression,
		arg.UserID,
		arg.CurrentLevel,
		arg.MilestonesCompleted,
		arg.TotalInspections,
	)
	var i SkillProgression
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentLevel,
		&i.MilestonesCompleted,
		&i.TotalInspections,
		&i.LastAssessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
