// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, email, display_name, experience_level, region)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, firebase_uid, email, display_name, experience_level, region, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FirebaseUid     string `json:"firebase_uid"`
	Email           string `json:"email"`
	DisplayName     string `json:"display_name"`
	ExperienceLevel string `json:"experience_level"`
	Region          string `json:"region"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.ExperienceLevel,
		arg.Region,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, experience_level, region, created_at, updated_at, deleted_at FROM users WHERE firebase_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, display_name, experience_level, region, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users SET display_name = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, firebase_uid, email, display_name, experience_level, region, created_at, updated_at, deleted_at
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, experience_level = $3, region = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, firebase_uid, email, display_name, experience_level, region, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	DisplayName     string      `json:"display_name"`
	ExperienceLevel string      `json:"experience_level"`
	Region          string      `json:"region"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.ExperienceLevel,
		arg.Region,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.ExperienceLevel,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
